name: video_metadata_example
description: "Demonstrates how to use the video_metadata plugin."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  video_metadata:
    path: ../
  path_provider: ^2.1.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Sample video is taken from
  # https://file-examples.com/index.php/sample-video-files/
  assets:
    - assets/MP4_SAMPLE_480_1_5MG.mp4
